### ISSUE TITLE
Unable to add Attrib's

### ISSUE THREAD

**Issue by iptvcld** [ReneNulschDE/mbapipy#18]
I have this in my json:
"doorsClosed": "true", "parkbrakestatus": "true", "carAlarm": "ON", "engineHoodClosed": "true", "locked": "true"
And i would like to add carAlarm and engineHoodClosed but i am not sure where to enable this.

**Comment by ReneNulschDE** [comment]
I have added the attributes to the Master Branch. Let me know if it works for you then I will push a new version.

**Comment by iptvcld** [comment]
Thank you! - i updated the apicontrollor.py file and i now see the below:
- Looks like only the hoodclosed came through.

retrievalstatus: VALID
doorStateFrontRight: DOOR_CLOSED_AND_DOOR_LOCKED
doorStateRearRight: DOOR_CLOSED_AND_DOOR_LOCKED
doorStateRearLeft: DOOR_CLOSED_AND_DOOR_LOCKED
sunroofstatus: TILT_SLIDE_SUNROOF_CLOSED
doorsClosed: true
trunkStateRollup: CLOSED_AND_LOCKED
doorStateFrontLeft: DOOR_CLOSED_AND_DOOR_LOCKED
engineHoodClosed: true
friendly_name: platenumber Lock

**Comment by ReneNulschDE** [comment]
you have to update the const.py too

**Comment by iptvcld** [comment]
sorry about that;  i have updated that file as well and below is the output
retrievalstatus: VALID
engineHoodClosed: true
doorStateRearLeft: DOOR_CLOSED_AND_DOOR_LOCKED
trunkStateRollup: CLOSED_AND_LOCKED
doorStateFrontRight: DOOR_CLOSED_AND_DOOR_LOCKED
doorStateRearRight: DOOR_CLOSED_AND_DOOR_LOCKED
doorsClosed: true
doorStateFrontLeft: DOOR_CLOSED_AND_DOOR_LOCKED
sunroofstatus: TILT_SLIDE_SUNROOF_CLOSED
friendly_name: plate Lock

**Comment by ReneNulschDE** [comment]
Could you send me a private message in the forum with your feat_*.json and state_*.json

**Comment by iptvcld** [comment]
the forum is only accepting picture formats

**Comment by ReneNulschDE** [comment]
carAlarm is not available in the states api. I'll remove the attribute again.
