### ISSUE TITLE
MercedesMe needs rework in HA 0.110

### ISSUE THREAD

**Issue by dvd77** [ReneNulschDE/mbapipy#20]
It needs rework after update to 0.11
BinarySensorDevice is deprecated, modify MercedesMEBinarySensor to extend BinarySensorEntity

**Comment by ReneNulschDE** [comment]
this is already done. please check master branch or the latest prerelease.

**Comment by dvd77** [comment]
sorry, hacs didnt update yet. 0.37 is working now. Thnx
