### ISSUE TITLE
Inconsistent naming of entities

### ISSUE THREAD

**Issue by spacegaier** [ReneNulschDE/mbapipy#23]
Most generated entities follow a nice naming schema (separate words with capital start letters).

Fuel Level
Tire Warning
...

However, there are a few that break the schema and look weird, e.g. the switches:

https://github.com/ReneNulschDE/mbapipy/blob/492b6242689158cf1e2fba1eac4a4bdf72d45faa/custom_components/mercedesmeapi/const.py#L113-L133

|Current|Proposal|
|---|---|
|AUX HEAT| Aux Heat|
|CLIMATE CONTROL|Climate Control
|REMOTE START |Remote Start|
|Range electric|Range Electric|
|auxheat status|Aux Heat Status|

To not break existing setups, the entity IDs would need to stay the same (unless you are fine with a simple to fix breaking change), so both the name as well as the entity ID would need to be passed from the custom component to HA. That seems to already be the case though: https://github.com/ReneNulschDE/mbapipy/blob/master/custom_components/mercedesmeapi/__init__.py#L178

**Comment by ReneNulschDE** [comment]
I have pushed an update to the master branch. All fixed except "Auxheat status" - this would break existing setups. Please use the manual renaming in HA to adjust this.

**Comment by spacegaier** [comment]
> All fixed except "Auxheat status" - this would break existing setups. Please use the manual renaming in HA to adjust this.

Yes, I saw that unfortunately not the key but actually the name is used for the unique ID, which is a pitty.

Two more somewhat related things:

1. How do those changes end up as updates in HACS? Is HACS automatically pulling those changes every so often?
2. Is the "odometer" here correct? https://github.com/ReneNulschDE/mbapipy/blob/7579003a77fa3fc6d59b5b0262e867c12ca525bf/custom_components/mercedesmeapi/const.py#L190

**Comment by ReneNulschDE** [comment]
I will take it on my list of things that should be rewritten.

1. HACS will show the Update option as soon as I push a new release here. However, you could use the Reinstall Option and select the Master branch.

2. Yes, should be correct. I create an object odometer in the underlaying API (apicontroller.py) https://github.com/ReneNulschDE/mbapipy/blob/7579003a77fa3fc6d59b5b0262e867c12ca525bf/custom_components/mercedesmeapi/apicontroller.py#L72
